RM := rm -rf
BRIDGE_EXE := studio-mdk-bridge.exe
UV4_EXE := "C:\Keil_v5\UV4\UV4.exe"
UVPROJX_LOC := "C:\Users\Utente\Documents\GitHub\Assignment_Embedded_OS\rtthread_simulator_0.1.0_en\project.uvprojx"

.PHONY: mdk_all

mdk_all:
	-$(BRIDGE_EXE) --build --uv4-path $(UV4_EXE) $(UVPROJX_LOC)

mdk_clean:
	-@$(RM) *
	@echo 'success'



*.elf: $(wildcard ..)
